version: "3.8"
services:
  itel-fhir:
    build:
      context: .
      dockerfile: Dockerfile.ibm-fhir-custom
    ports:
      - "9443:9443"
      - "9442:9442"
  smarteven-mock:
    build:
      context: .
      dockerfile: Dockerfile.smarteven-mock
    ports:
      - "8081:8081"
    restart: always
    environment:
      - smarteven.mock.health-adapter-base-url=http://healthadapter:8080
      - fhir-server-host=itel-fhir
      - fhir-server-port=9442
  healthadapter:
    build:
      context: .
      dockerfile: Dockerfile.healthadapter
    ports:
      - "8080:8080"
    restart: always
    environment:
      - embedded.containers.enabled=false
      - fhir-server-host=itel-fhir
      - fhir-server-port=9442